name: Análisis con SonarQube

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    name: Analizar con SonarQube
    runs-on: ubuntu-latest
    
    steps:
    - name: Descargar código
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requerimientos.txt ]; then pip install -r requerimientos.txt; fi
        
    - name: Ejecutar análisis de SonarQube
      uses: SonarSource/sonarqube-scan-action@v4
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.projectKey=servidor702
          -Dsonar.projectName=servidor702
          -Dsonar.sources=.
          -Dsonar.exclusions=**/node_modules/**,**/*.pyc,**/__pycache__/**
